/* generated by unplugin-react-components */
export {}
declare global{
	const Layout: typeof import('./src/layout/index')['default']
	const NotFound: typeof import('./src/view/404')['default']
	const Dashboard: typeof import('./src/view/dashboard/index')['default']
}